### ISSUE TITLE
segment fault in hydra 8.6 in termux 

### ISSUE THREAD

**Issue by 1Tech-X** [ldidry/dynamic-motd#3]
$hydra -l admin -P pass.txt 192.168.0.1 http-get
Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-08-14 00:28:13
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
Segmentation fault
can anybody fix this issue

**Comment by ldidry** [comment]
I think you created an issue on the wrong repo…

**Comment by 1Tech-X** [comment]
ok
