### ISSUE TITLE
Login takes forever

### ISSUE THREAD

**Issue by microfx** [ldidry/dynamic-motd#5]
Hey!

Since I am using this on   Raspbian GNU/Linux 10 (buster) (kernel 4.19.71-rt24-v7+) login is taking like 1 min. Any idea?

**Comment by ldidry** [comment]
Could you try after a reboot or a restart of systemd-logind: it happened to me in the past and this solved it for me.

**Comment by microfx** [comment]
It's a bit faster now but still around 20 seconds ...weird...

**Comment by microfx** [comment]
So that was "one" of the solutions – thanks for the super quick answer. For anyone else reading this: I also set this in /etc/ssh/sshd_config 

UseDNS no
UsePAM no

Now it's blazingly fast.
