### ISSUE TITLE
Not working on Debian 11

### ISSUE THREAD

**Issue by yuljk** [ldidry/dynamic-motd#6]
Hi - After upgrading to Debian 11 from 10, the MOTD no longer displays system information.  I have installed python3-utmp as mentioned.

I've also updated 20-system-info for python3.  I didn't see any references to python in sysinfo.py

If I run python3 /etc/update-motd.d/sysinfo.py I get the following.

File "/etc/update-motd.d/sysinfo.py", line 72
    print "  System information as of %s\n" % time.asctime()
            ^
SyntaxError: invalid syntax

Any ideas?
Many thanks

**Comment by ldidry** [comment]
Update the [python script](https://github.com/ldidry/dynamic-motd/blob/master/update-motd.d/sysinfo.py) then do
```
sed -e "s/python/python3/g" 20-system-info sysinfo.py
```

(The python and the instructions on the README have been updated 25 days ago).
